name: Mirror Node.JS

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Node.JS version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          set -e

          # https://github.com/nodejs/node#release-keys
          gpg --keyserver hkps://keys.openpgp.org --recv-keys 4ED778F539E3634C779C87C6D7062848A1AB005C
          gpg --keyserver hkps://keys.openpgp.org --recv-keys 141F07595B7B3FFE74309A937405533BE57C7D57
          gpg --keyserver hkps://keys.openpgp.org --recv-keys 74F12602B6F1C4E913FAA37AD3A89613643B6201
          gpg --keyserver hkps://keys.openpgp.org --recv-keys DD792F5973C6DE52C432CBDAC77ABFA00DDBF2B7
          gpg --keyserver hkps://keys.openpgp.org --recv-keys 8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600
          gpg --keyserver hkps://keys.openpgp.org --recv-keys C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8
          gpg --keyserver hkps://keys.openpgp.org --recv-keys 890C08DB8579162FEE0DF9DB8BEAB4DFCF555EF4
          gpg --keyserver hkps://keys.openpgp.org --recv-keys C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C
          gpg --keyserver hkps://keys.openpgp.org --recv-keys 108F52B48DB57BB0CC439B2997B01419BD92F80A
          gpg --keyserver hkps://keys.openpgp.org --recv-keys A363A499291CBBC940DD62E41F10027AF002F8B0

          curl -O https://nodejs.org/dist/v${{ github.event.inputs.version }}/SHASUMS256.txt
          curl -O https://nodejs.org/dist/v${{ github.event.inputs.version }}/SHASUMS256.txt.sig
          gpg --verify SHASUMS256.txt.sig SHASUMS256.txt

          files="SHASUMS256.txt SHASUMS256.txt.sig"
          while read -r line; do
            hash=$(echo $line | cut -d ' ' -f 1)
            file=$(echo $line | cut -d ' ' -f 2)

            if [[ $file == */* ]]; then
              continue
            fi

            curl -O https://nodejs.org/dist/v${{ github.event.inputs.version }}/$file
            echo "$hash $file" | sha256sum -c -
            files="$files $file"
          done < SHASUMS256.txt

          gh release create v${{ github.event.inputs.version }} $files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}