name: Mirror Node.JS

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          set -e

          # Download the trusted keyring from nodejs/release-keys
          # https://github.com/nodejs/node#verifying-binaries
          curl -fsLo "/tmp/nodejs-keyring.kbx" "https://github.com/nodejs/release-keys/raw/HEAD/gpg/pubring.kbx"

          curl --no-progress-meter -O https://nodejs.org/dist/index.json

          versions=$(cat << EOF | node
          const fs = require('fs');
          const builds = JSON.parse(fs.readFileSync('index.json', 'utf8'));
          const versions = builds.map(build => build.version)
            .filter(version => parseInt(/^v(\d+)\./.exec(version)[1]) >= 18);
          console.log(versions.join('\n'));
          EOF
          )

          for version in $versions; do
            if gh release view $version > /dev/null; then
              echo "Release $version already exists"
              continue
            fi

            mkdir -p $version
            pushd $version

            curl --no-progress-meter -O https://nodejs.org/dist/$version/SHASUMS256.txt.asc

            if ! gpgv --keyring="/tmp/nodejs-keyring.kbx" --output SHASUMS256.txt < SHASUMS256.txt.asc; then
              echo "Skipping $version since signature verification failed"
              continue
            fi

            files="SHASUMS256.txt SHASUMS256.txt.asc"
            while read -r line; do
              hash=$(echo $line | cut -d ' ' -f 1)
              file=$(echo $line | cut -d ' ' -f 2)

              if [[ $file == */* ]]; then
                continue
              fi

              curl --no-progress-meter -O https://nodejs.org/dist/$version/$file
              echo "$hash $file" | sha256sum -c -
              files="$files $file"
            done < SHASUMS256.txt

            gh release create $version $files
            echo "Successfully created release $version"

            popd
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
